Pull request for Portfolio Project
GraceAbike/Portfolio pull request #1
Opened 2022-06-29 06:33 UTC by GraceAbike

2022-06-29 09:34 UTC, Bondok6 requested changes
## Hi @GraceAbike🙋‍♂️ , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights
- All linters are passing ✅
- Good commit history 💯✅
- Great job on implementing the project ✅💯

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 09:34 UTC, Bondok6 commented on index.html
> +  </section>
- [ ] I noticed that this section has more space on the right side, please fix it. Remember you should stick to the design as much as possible (e.g. font, colors, images, tests, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)

| Your Design  | Figma Design  |   
| --- | --- |
| <img src="https://user-images.githubusercontent.com/45231276/176401378-a31cb43f-ed59-4331-a828-3d433873b1ec.PNG" width="500" />   | <img src="https://user-images.githubusercontent.com/45231276/176401541-4eaac748-2a12-4dcd-a987-adaa1d247156.PNG" width="500" /> |

2022-06-29 09:34 UTC, Bondok6 commented on index.html
> +      <a href="#" class="connect">Let's Connect</a>
- [ ] According to the requirements, You should Implement the button interactions (enable, hover, etc.). so I suggest adding a hove on the `connect` class.

For example
```
a.connect:hover {
  color: #fff;
  background-color: #7f8cff;
}
```

![image](https://user-images.githubusercontent.com/45231276/176402228-2c9255aa-c65f-4928-bbaf-375ec41b19ff.png)

2022-06-29 09:34 UTC, Bondok6 commented on index.html
> +    <nav class="des"></nav>
- [OPTIONAL] I suggest deleting this line (I think it is not necessary) to make the code clean.

2022-06-29 09:34 UTC, Bondok6 commented on test.yml
> +"This test file should ignore by git"
- [OPTIONAL] I suggest deleting this file (I think it is not necessary) to make the code clean.

2022-06-29 09:34 UTC, Bondok6 commented on index.html
> +  </nav>
- [ ] Great job for using the semantic HTML tags correctly 💯. However, according to the requirements, You must stick to the design as much as possible (e.g. font, colors, images, tests, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). I noticed that the alignment between the logo and the menu icon is not the same as the Figma design, kindly fix it.

| Your Design  | Figma Design  |   
| --- | --- |
| <img src="https://user-images.githubusercontent.com/45231276/176397711-b32acf9b-4f03-47fb-a307-71b96adb96bd.png" width="500" />   | <img src="https://user-images.githubusercontent.com/45231276/176398022-271f78cb-a5bc-46a8-bfc5-33867021eede.png" width="500" /> |

2022-07-01 11:16 UTC, GraceAbike commented on index.html
> +  </section>
thank you very much, I have made the changes

2022-07-01 11:32 UTC, DammyShittu approved these changes
Hi @GraceAbike,

## APPROVED 🟢

✔️ Nice styling

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 11:57 UTC, merged

2022-07-01 12:00 UTC, GraceAbike commented
Thanks to you all, I'm happy to complete the project.